# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_Image.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow,Height,Width):
        MainWindow.setObjectName("MainWindow")
        self.Height = Height
        self.Width = Width
        MainWindow.resize(self.Width, self.Height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.RWidth = ((89 / 100) * self.Width)
        self.RHeight = ((99 / 100) * self.Height)
        self.label1.setGeometry(QtCore.QRect(140, -10, self.RWidth, self.RHeight))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 1, 141, self.RHeight))
        self.listView.setObjectName("listView")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(0, 30, 131, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(-100)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setValue(0)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(5)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 67, 17))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(0, 80, 131, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setMinimum(-90)
        self.horizontalSlider_2.setMaximum(90)
        self.horizontalSlider_2.setValue(0)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_2.setTickInterval(5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 81, 17))
        self.label_3.setObjectName("label_3")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(0, 130, 131, 16))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_3.setMinimum(-100)
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_3.setValue(0)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 67, 17))
        self.label_4.setObjectName("label_4")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(0, 180, 131, 16))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_4.setMinimum(-180)
        self.horizontalSlider_4.setMaximum(180)
        self.horizontalSlider_4.setValue(0)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 81, 17))
        self.label_5.setObjectName("label_5")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(0, 240, 131, 16))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_5.setMaximum(100)
        self.horizontalSlider_5.setMinimum(0)
        self.horizontalSlider_5.setValue(0)
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(10, 310, 50, 64))
        self.dial.setObjectName("dial")
        self.dial.setMaximum(360)
        self.dial.setMinimum(0)
        self.dial.setValue(0)
        self.dial.setWrapping(True)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 280, 67, 17))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 380, 121, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 420, 121, 25))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(106, 40, 31, 20))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 90, 31, 20))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(110, 140, 31, 20))
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(110, 190, 31, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(110, 250, 31, 20))
        self.label_15.setObjectName("label_15")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 320, 31, 31))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuImage = QtWidgets.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        self.menuFilter = QtWidgets.QMenu(self.menubar)
        self.menuFilter.setObjectName("menuFilter")
        self.menuColor_Map = QtWidgets.QMenu(self.menuFilter)
        self.menuColor_Map.setObjectName("menuColor_Map")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionEdge_Detection = QtWidgets.QAction(MainWindow)
        self.actionEdge_Detection.setObjectName("actionEdge_Detection")
        self.actionConvert_GrayScale = QtWidgets.QAction(MainWindow)
        self.actionConvert_GrayScale.setObjectName("actionConvert_GrayScale")
        self.actionInvert = QtWidgets.QAction(MainWindow)
        self.actionInvert.setObjectName("actionInvert")
        self.actionAUTUMN = QtWidgets.QAction(MainWindow)
        self.actionAUTUMN.setObjectName("actionAUTUMN")
        self.actionBONE = QtWidgets.QAction(MainWindow)
        self.actionBONE.setObjectName("actionBONE")
        self.actionJET = QtWidgets.QAction(MainWindow)
        self.actionJET.setObjectName("actionJET")
        self.actionWINTER = QtWidgets.QAction(MainWindow)
        self.actionWINTER.setObjectName("actionWINTER")
        self.actionRAINBOW = QtWidgets.QAction(MainWindow)
        self.actionRAINBOW.setObjectName("actionRAINBOW")
        self.actionOCEAN = QtWidgets.QAction(MainWindow)
        self.actionOCEAN.setObjectName("actionOCEAN")
        self.actionSUMMER = QtWidgets.QAction(MainWindow)
        self.actionSUMMER.setObjectName("actionSUMMER")
        self.actionSPRING = QtWidgets.QAction(MainWindow)
        self.actionSPRING.setObjectName("actionSPRING")
        self.actionCOOL = QtWidgets.QAction(MainWindow)
        self.actionCOOL.setObjectName("actionCOOL")
        self.actionHSV = QtWidgets.QAction(MainWindow)
        self.actionHSV.setObjectName("actionHSV")
        self.actionPINK = QtWidgets.QAction(MainWindow)
        self.actionPINK.setObjectName("actionPINK")
        self.actionHOT = QtWidgets.QAction(MainWindow)
        self.actionHOT.setObjectName("actionHOT")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuImage.addAction(self.actionHistogram)
        self.menuImage.addAction(self.actionEdge_Detection)
        self.menuImage.addAction(self.actionConvert_GrayScale)
        self.menuImage.addAction(self.actionInvert)
        self.menuColor_Map.addAction(self.actionAUTUMN)
        self.menuColor_Map.addAction(self.actionBONE)
        self.menuColor_Map.addAction(self.actionJET)
        self.menuColor_Map.addAction(self.actionWINTER)
        self.menuColor_Map.addAction(self.actionRAINBOW)
        self.menuColor_Map.addAction(self.actionOCEAN)
        self.menuColor_Map.addAction(self.actionSUMMER)
        self.menuColor_Map.addAction(self.actionSPRING)
        self.menuColor_Map.addAction(self.actionCOOL)
        self.menuColor_Map.addAction(self.actionHSV)
        self.menuColor_Map.addAction(self.actionPINK)
        self.menuColor_Map.addAction(self.actionHOT)
        self.menuFilter.addAction(self.menuColor_Map.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Brightness"))
        self.label_2.setText(_translate("MainWindow", "Contrast"))
        self.label_3.setText(_translate("MainWindow", "Saturation"))
        self.label_4.setText(_translate("MainWindow", "Hue"))
        self.label_5.setText(_translate("MainWindow", "Sharpness"))
        self.label_6.setText(_translate("MainWindow", "Rotate"))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "0"))
        #self.label_13.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "Flip Horizontally"))
        self.pushButton_2.setText(_translate("MainWindow", "Flip Vertically"))
        #self.label_7.setText(_translate("MainWindow", "Blur"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuImage.setTitle(_translate("MainWindow", "Image"))
        self.menuFilter.setTitle(_translate("MainWindow", "Filters"))
        self.menuColor_Map.setTitle(_translate("MainWindow", "Color Map"))
        self.actionNew.setText(_translate("MainWindow", "Open"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionEdge_Detection.setText(_translate("MainWindow", "Edge Detection"))
        self.actionConvert_GrayScale.setText(_translate("MainWindow", "Convert GrayScale"))
        self.actionInvert.setText(_translate("MainWindow", "Invert"))
        self.actionAUTUMN.setText(_translate("MainWindow", "AUTUMN"))
        self.actionBONE.setText(_translate("MainWindow", "BONE"))
        self.actionJET.setText(_translate("MainWindow", "JET"))
        self.actionWINTER.setText(_translate("MainWindow", "WINTER"))
        self.actionRAINBOW.setText(_translate("MainWindow", "RAINBOW"))
        self.actionOCEAN.setText(_translate("MainWindow", "OCEAN"))
        self.actionSUMMER.setText(_translate("MainWindow", "SUMMER"))
        self.actionSPRING.setText(_translate("MainWindow", "SPRING"))
        self.actionCOOL.setText(_translate("MainWindow", "COOL"))
        self.actionHSV.setText(_translate("MainWindow", "HSV"))
        self.actionPINK.setText(_translate("MainWindow", "PINK"))
        self.actionHOT.setText(_translate("MainWindow", "HOT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())